<br>
<br>
<div class="example">
<h4>4. We customise Magento menu widget, force it show mobile view and use it as a sidebar menu.</h4>
  <nav class="bifang-menu navigation" data-action="navigation">
      <ul data-mage-init='{
        "bifangMenu":{
          "responsive":true,
          "expanded":true,
          "mediaBreakpoint": "(min-width: 0px)"
        }
      }'>
        <li class="level0 category-item level-top first parent"><a href="http://www.yangmgt23.com/women.html" class="level-top"><span>Women</span></a>
          <ul class="level0 submenu">
            <li class="level1 category-item first parent"><a href="http://www.yangmgt23.com/women/bottoms-women.html"><span>Bottoms</span></a>
              <ul class="level1 submenu">
                <li class="level2 category-item first"><a href="http://www.yangmgt23.com/women/bottoms-women/pants-women.html"><span>Pants</span></a></li>
                <li class="level2 category-item last"><a href="http://www.yangmgt23.com/women/bottoms-women/pants-women.html"><span>Shorts</span></a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="level0 category-item level-top parent"><a href="http://www.yangmgt23.com/gear.html" class="level-top"><span>Gear</span></a>
          <ul class="level0 submenu">
            <li class="level1 category-item first"><a href="http://www.yangmgt23.com/gear/bags.html"><span>Bags</span></a></li>
            <li class="level1 category-item"><a href="http://www.yangmgt23.com/gear/fitness-equipment.html"><span>Fitness Equipment</span></a></li>
            <li class="level1 category-item last"><a href="http://www.yangmgt23.com/gear/watches.html"><span>Watches</span></a></li>
          </ul>
        </li>
        <li class="level0 category-item last level-top"><a href="http://www.yangmgt23.com/sale.html" class="level-top"><span>Sale</span></a></li>
      </ul>
  </nav>

</div>
