<h2>Here are examples of Magento
  <a target="_blank" href="https://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html">
    UI Component
  </a>
</h2>
<ul>
  <li>The followings are an order list and an invoice list.</li>
  <li>These lists are generated through listing UiComponent</li>
  <li>The data is collected by a DataProvider Ojbect</li>
  <li>If you look in to the magento source code, you can find two different DataProviders:
    <ul>
      <li> 1. Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider: This DataProvider applies Search API, so that you can filter out objects by attributes.</li>
      <li> 2. Magento\Ui\DataProvider\AbstractDataProvider: This DataProvider does not apply Search API, but the structure is much simpler.</li>
    </ul>
  </li>
</ul>
